apiVersion: v1 

kind: Service 

metadata: 

  name: {{ .Values.nginx.servicename }}

spec: 

  type: NodePort 

  selector: 

    app: {{ .Values.nginx.name }}

  ports: 

  - port:  {{ .Values.nginx.port }} # Port on which the application is listening 

    targetPort: 80 # Port on which the application is listening 
