apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: nginx-httpd
    annotations:
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: instance
        kubernetes.io/ingress.class: alb
#        alb.ingress.kubernetes.io/subnets: subnet-05e1c98ed0f5b109e,subnet-07f5bb81f661df61b,subnet-0a4e6232630820516
        alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
#        alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTP": 9201}]'
spec:
    rules:
#    - host: echoserver.example.com
     - http:
        paths:
          - path:  /*
            backend: 
               serviceName:  "nginxservice"                 ##{{ .Values.nginx.servicename }}
               servicePort: 80
##second service ####### 
          - path: /*
            backend:
              serviceName: "httpdservice"
              servicePort: 80



